language: python
python:
- '3.6'
sudo: required
dist: trusty
branches:
  only:
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install:
- make install-deps
script:
- make build VERSION=$TRAVIS_TAG
deploy:
- provider: pypi
  on:
    tags: true
    all_branches: true
  username: phoenix.lv
  password:
    secure: Z3HKyidDI1duYGdxWDMv0o+XC9D2bQYJuzOBCbvF08o/UT9S4zDnMA0Rb+aOzZOH9xbKBF9E4vjbnkhs8Vi7gqhq7faC8ObBbocDB/VsYiJW2RDBuL8oNk3cy0ncgLSOVPQsJnoY0jF7vvdMEYuixXRxUBmbC8sQFwy788nwG17yeAX3FH5JFQLN81AWte+cdlpeLPZIK8kkrUJ+zo8tADMeLOmD9nhebm1tRXgMVqTgOY8b/bgKuUkG1Q+wLQEdd7pQrxWi9ZLC1q9qWvst5s0L15gF0sVBK5uBDJkSxEJ7DWWtAnEe/h9MeblbAw+/HUTfi4A77xrqV6Md+Jfx352ufDfKsKQ+O41T27iXBwUpGdNHV6ViGgb9YjcZ4cKO/FGjaabUvXfXxjiRRePDhWNlcpX3KPfffi9S1C4SeEBWVLBTalamchVxrx8KMXGQinKS2GeEIIB8LosgIxYDRa0HhZWNoIx0Hg9kfrYzO3PY0/kTIedB9Od2fWrs9I0q3PthymScjhaTKtUdpvs1aT/YOYqjtY7bJ9b+h019zcqlT6OtHq/F1s5ACuCAHB99VWIvt+9F/lbNQnhcqM4G2qN9FPO4t04FQN5D6+GphfxIObIVMh0QVbS6nC/FBW6LNXDOdwBndnUEsvxudSlzxD+VXFcBMLV3CKRaTM4u1PQ=
